### ISSUE TITLE
Requests fails with consul exception

### ISSUE THREAD

**Issue by deejay1** [RulersOfAsgard/requests-consul#9]
We shouldn't fail with just a consul exception, we should raise a custom RequestsException instead...

sample fail:
```python
Apr 15 13:41:30 alamo-worker2 alamo_worker_52[10343]: Traceback (most recent call last):   File "/srv/alamo_worker/bin/alamo-worker", line 10, in <module>     sys.exit(main())   File "/srv/alamo_worker/lib/p
ython3.4/site-packages/alamo_worker/cli.py", line 135, in main     management.execute()   File "/srv/alamo_worker/lib/python3.4/site-packages/alamo_worker/cli.py", line 124, in execute     result = self.mana
ger.dispatch(check)   File "/srv/alamo_worker/lib/python3.4/site-packages/alamo_worker/plugins/__init__.py", line 161, in dispatch     _plugin.execute(payload)   File "/srv/alamo_worker/lib/python3.4/site-pa
ckages/alamo_worker/plugins/http_check.py", line 89, in execute     response = call_method(**call_kwargs)   File "/srv/alamo_worker/lib/python3.4/site-packages/requests/sessions.py", line 480, in get     ret
urn self.request('GET', url, **kwargs)   File "/srv/alamo_worker/lib/python3.4/site-packages/requests/sessions.py", line 468, in request     resp = self.send(prep, **send_kwargs)   File "/srv/alamo_worker/li
b/python3.4/site-packages/requests/sessions.py", line 576, in send     r = adapter.send(request, **kwargs)   File "/srv/alamo_worker/lib/python3.4/site-packages/requests/adapters.py", line 343, in send     c
onn = self.get_connection(request.url, proxies)   File "/srv/alamo_worker/src/requests-consul/requests_consul/adapters/service.py", line 119, in get_connection     url = self._build_instance_url(parsed).getu
rl()   File "/srv/alamo_worker/src/requests-consul/requests_consul/adapters/service.py", line 81, in _build_instance_url     instances = self._fetch_instances(service_name)   File "/srv/alamo_worker/src/requ
ests-consul/requests_consul/adapters/service.py", line 73, in _fetch_instances     service_name, dc=dc)[1])   File "/srv/alamo_worker/lib/python3.4/site-packages/consul/base.py", line 1145, in service     '/
v1/catalog/service/%s' % service, params=params)   File "/srv/alamo_worker/lib/python3.4/site-packages/consul/std.py", line 34, in get     self.session.get(uri, verify=self.verify)))   File "/srv/alamo_worke
r/lib/python3.4/site-packages/consul/base.py", line 111, in cb     raise ConsulException("%d %s" % (response.code, response.body)) consul.base.ConsulException: 500 No cluster leader\
```

**Comment by adamdubiel** [comment]
How about retry couple times?

**Comment by deejay1** [comment]
Well, we could for the next release, question is how many times should we do it ?

**Comment by adamdubiel** [comment]
Configurable, default: 3 ;)
